### ISSUE TITLE
[BUG] Society Fund Not Updating

### ISSUE THREAD

**Issue by Aimeri** [qbcore-framework/qb-management#56]
**Describe the bug**
After a bill is paid, the society fund total will be updated in the database but upon going to the Boss Menu and checking there, the society fund amount doesn't update to reflect the new amount.

**To Reproduce**
1. Be employed at a business.
2. Send someone a bill from that business.
3. After that person pays their bill, check the SQL database.  You'll see the amount has been updated correctly.
4. Access boss menu for mentioned job and check the Society Fund amount.   You'll see it's not updated to match the new amount.

**Expected behavior**
It would be expected that the boss menu's society fund would update to reflect what is shown in the database.

**Screenshots**
![image](https://user-images.githubusercontent.com/3940622/171917858-8ef36997-0ba6-4169-9335-f108696a7eb7.png)
![image](https://user-images.githubusercontent.com/3940622/171917922-5b66d8c2-2701-4cac-8014-259948e05424.png)

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week] : **I updated half an hour ago.**
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target] : **I am using g-billing to send/receive the bills.**
 - Have you renamed `qb-` to something custom? [e.g. yes/no] **No I have not renamed qb- to anything else.**

**Comment by nullvariable** [comment]
hello @Aimeri thanks for reporting this and putting all the details in!
I've had a look, and assuming that you're using the `g-billing` resource I found here: https://github.com/Giana/g-billing/blob/master/server/main.lua#L78 it looks like it is updating the database directly, which causes the boss menu not to show the latest data. The `g-billing` resource should be updated to use a pattern like
```
exports['qb-management']:AddMoney("mechanic", 1234)
```
instead of updating the database directly if you want the boss menu to show the information in real time.
